tabWidth: 2
singleQuote: false
useTabs: false

overrides:
  - files:
      - "*.md"
    options:
      tabWidth: 2
      embeddedLanguageFormatting: "auto"

  - files:
      - "*.yml"
      - "*.yaml"
    options:
      tabWidth: 2
      proseWrap: "preserve"

  - files:
      - "*.sh"
      - "*.bash"
    options:
      tabWidth: 2
      parser: "sh"
